"""Canonical production calibrator entry point.

The calibration path explicitly installs the strictly-causal baseline before
loading any historical cases. A dedicated versioned cache namespace prevents
reuse of residuals generated by older baseline implementations.
"""
from dataclasses import asdict
from pathlib import Path

from .. import causal_baseline
from .. import production_grade_validation as pg

# Force every historical-case preparation call through the same causal
# residual generator used by the production detector path.
pg.pm.compute_qdc_baseline = causal_baseline.compute_causal_qdc_baseline

# Deliberately advance this namespace after prior runs: calibration must be
# recomputed from raw INTERMAGNET data, not inherited from uncertain caches.
pg.DEFAULT_CACHE_DIR = Path(__file__).resolve().parents[1] / "data" / "case_cache_causal_v5"

from .. import calibrate_detector as _impl  # noqa: E402

_original_coordinate_descent = _impl._coordinate_descent


def _converged_coordinate_descent(cases, base, max_passes=3):
    """Run the existing safe coordinate search repeatedly until stable.

    The underlying search already enforces the production-floor ordering and
    conservative regularization. Repeating it lets interacting parameters
    (for example peak evidence + hysteresis timing) reach a joint local optimum
    instead of freezing after the first parameter sweep.
    """
    profile = base
    for _ in range(max_passes):
        candidate = _original_coordinate_descent(cases, profile)
        if asdict(candidate) == asdict(profile):
            break
        profile = candidate
    return profile


_impl._coordinate_descent = _converged_coordinate_descent
main = _impl.main

if __name__ == "__main__":
    main()
