"""Canonical production calibrator entry point.

The calibration path explicitly installs the strictly-causal baseline before
loading any historical cases. A dedicated cache namespace prevents reuse of
residuals generated by older, non-causal baseline implementations.
"""
from pathlib import Path

from .. import causal_baseline
from .. import production_grade_validation as pg

# Force every historical-case preparation call through the same causal
# residual generator used by the production detector path.
pg.pm.compute_qdc_baseline = causal_baseline.compute_causal_qdc_baseline

# Never reuse caches generated by the pre-causal validation path.
pg.DEFAULT_CACHE_DIR = Path(__file__).resolve().parents[1] / "data" / "case_cache_causal_v3"

from ..calibrate_detector import main  # noqa: E402

if __name__ == "__main__":
    main()
